include:
  - authentication-microservice/.gitlab-ci.yml
  - example-microservice/.gitlab-ci.yml
  - requirements-microservice/.gitlab-ci.yml
  - voting-microservice/.gitlab-ci.yml
  - hoa-microservice/.gitlab-ci.yml
  - commons/.gitlab-ci.yml