image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-commons:
  stage: build
  script:
    gradle commons:assemble commons:testClasses

checkStyle-commons:
  stage: staticAnalysis
  script:
    gradle commons:checkstyleMain commons:checkStyleTest
  allow_failure: true


PMD-commons:
  stage: staticAnalysis
  script:
    gradle commons:pmdMain
  allow_failure: true
