image: gradle:6.7-jdk15

stages:
  - build
  - staticAnalysis
  - test

variables:
  # Disable the Gradle daemon to ensure isolated runs of the CI pipeline.
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

build-hoa-microservice:
  stage: build
  script:
    gradle hoa-microservice:assemble hoa-microservice:testClasses

checkStyle-hoa-microservice:
  stage: staticAnalysis
  script:
    gradle hoa-microservice:checkstyleMain hoa-microservice:checkStyleTest
  allow_failure: true


PMD-hoa-microservice:
  stage: staticAnalysis
  script:
    gradle hoa-microservice:pmdMain
  allow_failure: true

test-hoa-microservice:
  stage: test
  script:
    - gradle hoa-microservice:test hoa-microservice:jacocoTestReport
    - ( cat hoa-microservice/build/reports/jacoco/test/html/index.html | grep -Po "Total.*?([0-9]{1,3})%" ) || echo "No report has been generated - 0%"
  coverage: /([0-9]{1,3})%/
